### ISSUE TITLE
Implement 3D Unet

### ISSUE THREAD

**Issue by myychal** [PiechaczekMyller/brats#1]
Implement working 3D Unet architecture. One of my concerns is that volumes might have different number of slices. The network should deal with that.

**Comment by szympie** [comment]
It should not matter with 3D convolution.

**Comment by szympie** [comment]
Padding and transposed convolution needed to be done in a way that they have kernel_size = (1,2,2) and stride (1,2,2). I need to ask Kuba about it.

**Comment by szympie** [comment]
#19
