### ISSUE TITLE
Implement preprocessing script

### ISSUE THREAD

**Issue by myychal** [PiechaczekMyller/brats#2]
Write preprocessing code to structure, normalize and generate ready-to-feed data. One should keep in mind that it will be later needed to preprocessed Brats 2020(?) dataset. Also, final format of the data should be picked.

**Comment by myychal** [comment]
It is not clear to me whether the histogram matching operation should be performed. Also, I have noticed that the values are from range [0; ~3k], which is strange. 
As for the file format, .nii.gz appears to be a suitable one - its load time is fast and does not occupy too much memory.

**Comment by szympie** [comment]
I believe it should be performed as it should help with finding unusual regions (tumors) - e.g. the tumor would be 1,5 std away from the mean. However, I haven't done any literature review concerning this topic, this is just my intuition.

I also think, we should stick to .nii.gz format. I would also suggest to use torch/torchvision structure of datasets and its transformations (inherit from base classes). We could implement normalization/histogram matching and other kind of transformations relatively easy, with clear intentions how to use them.

**Comment by myychal** [comment]
I like the idea of using torch/torchvision classes for the preprocessing step. 
To my knowledge, histogram matching requires a template based on which the normalization is performed. We should somehow pick this template in the near future.

**Comment by myychal** [comment]
I am also wondering whether some kind of preprocessing step has already been done on the data we have.

**Comment by szympie** [comment]
I create an issue for this question #6

**Comment by myychal** [comment]
Here are some first result with a random template: [imgur](https://imgur.com/a/41codET)
_The implementation is heavily based on Michał M's_

**Comment by myychal** [comment]
#21
