### ISSUE TITLE
Find how to deal with uneven number of slices

### ISSUE THREAD

**Issue by szympie** [PiechaczekMyller/brats#25]
As the image downscales x2 with each step along each dimension, it is impossible for it to deal with images that are uneven in any dimension. In decathlon dataset (and brats as well), the number of slices is 155. 

How to deal with this problem? Add empty slice/copy 1 slice? 
Please, comment @jnalepa

**Comment by khrynczenko** [comment]
So is it a choice between removing one slice or adding one in an artificial way? I assume all slices are of the same height and with and its even.

**Comment by szympie** [comment]
Ok, rather than uneven, it should also be divisible by 16, so we need 5 more frames.

**Comment by myychal** [comment]
We have all agreed to add zero padding
